Parameters:
    SecurityGroupDescription:
      Description: Security Group Description(Simple Parameter)
      Type: String
    SecurityGroupPort:
      Description: simple Description of a number Parameter with MinValue and MaxValue
      Type: Number
      MinValue: 1150
      MaxValue: 65535
    InstanceType:
      Description: Webserver
      Type: String
      Default: t2.small
      AllowedValues:
        - t1.micro
        - t2.nano
        - t2.micro
        - t2.small
      ConstraintDescription: must be a valid EC2 instance type
    DBPwd:
      NoEcho: true
      Description: The database admin account password(wont be echoed)
      Type: String
    KeyName:
      Description: Name of an existing EC2 keypair to enable SSH access to the instances.
      Type: AWS::EC2::KeyPair::KeyName
      ConstraintDescription: Must be a name of existing EC2 keypair
    SecurityGroupIngressCIDR:
      Description: The IP address range that can be used to communicate to the EC2 instance
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
      ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
    MyVPC:
      Description: VPC to operate in
      Type: AWS::EC2::VPC::Id
    MySubnetIDs: 
      Description: Subnet IDs that is a list of subnet IDs
      Type: "List<AWS::EC2::Subnet::Id>"
    DBSubnetIpBlocks:
      Description: "Comma-delimeted list of three CIDR blocks"
      Type: String
      Default: "10.0.48.0/24"
  
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0d4c3eabb9e72650a
      SubnetId: !Ref DBSubnetIpBlocks

  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - CidrIp: !Ref SecurityGroupIngressCIDR
          FromPort: !Ref SecurityGroupPort
          ToPort: !Ref SecurityGroupPort
          IpProtocol: tcp
      VpcId: !Ref MyVPC